name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia à meia-noite (UTC)
  workflow_dispatch:        # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gerar gráfico 3D de contribuições
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: marcossbbatista

      - name: Publicar no branch "output"
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
